### ISSUE TITLE
CodeMirrorEditor exports breaks 3rd part JupyterLab extension loading

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-ui#170]
![Screenshot from 2024-01-09 10-47-13](https://github.com/datalayer/jupyter-ui/assets/226720/62510d19-94c8-43b0-8eb2-7da929a880a9)

**Comment by echarles** [comment]
For now, in https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/index.ts, the problematic have been temporary commented.

```ts
// CodeMirror Editor.
// TODO CodeMirrorEditor breaks the JupyterLab extension loading.
// export * from './components/codemirror/CodeMirrorEditor';

/ Outputs.
// TODO CodeMirrorEditor imported by Output breaks the JupyterLab extension loading.
// export * from './components/output/Output';
```

**Comment by echarles** [comment]
This does not happen anymore with the latest release. Closing

**Comment by echarles** [comment]
More symptoms on this issue

```
812.fa595a2be03628e77c9a.js?v=fa595a2be03628e77c9a:6 TypeError: Cannot read properties of undefined (reading 'deserialize')
    at setProp (index.js:1594:1)
    at new LRParser (index.js:1609:1)
    at LRParser.deserialize (index.js:1850:1)
    at ../../../node_modules/@lezer/python/dist/index.js (index.js:299:16)
    at __webpack_require__ (bootstrap:19:1)
    at ../../jupyter/ui/packages/react/node_modules/@codemirror/lang-python/dist/index.js (with-selector.js:7:1)
    at __webpack_require__ (bootstrap:19:1)
    at ../../jupyter/ui/packages/react/lib/components/codemirror/CodeMirrorEditor.js (ViewerComponent.tsx:24:32)
    at __webpack_require__ (bootstrap:19:1)
    at ../../jupyter/ui/packages/react/lib/components/output/Output.js (CodeMirrorTheme.ts:33:32)
```
