### ISSUE TITLE
Global CSS cannot be imported from node_modules

### ISSUE THREAD

**Issue by bugzpodder** [datalayer/jupyter-ui#184]
## Description

Related to #86 

Global CSS cannot be imported from node_modules

Cannot use datalyer/jupyter-react package in my nextjs app.

in components/

```
import { CellSidebar, Jupyter, Notebook } from "@datalayer/jupyter-react";

export default function JupyterExample() {
  return (
    <Jupyter
      jupyterServerHttpUrl="https://oss.datalayer.tech/api/jupyter"
      jupyterServerWsUrl="wss://oss.datalayer.tech/api/jupyter"
      jupyterToken="60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6"
    >
      <Notebook
        path="ipywidgets.ipynb"
        uid="notebook-nextjs-1"
        externalIPyWidgets={[
          { name: "@widgetti/jupyter-react", version: "0.3.0" },
          { name: "bqplot", version: "0.5.42" },
          { name: "jupyter-matplotlib", version: "0.11.3" },
        ]}
        cellSidebarMargin={120}
        CellSidebar={CellSidebar}
      />
    </Jupyter>
  );
}

```

in pages dir
```
const JupyterExample = dynamic(() => import("components/jupyter"), { ssr: false });
```

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- NextJS: 12.3.4, React: 18.2.0, yarn: 4
- Datalayer version:     "@datalayer/jupyter-react": "^0.8.3"
- Operating System and version:
- Browser and version:

<details><summary>Browser Output</summary>
<pre>

<img width="965" alt="Screenshot 2024-01-19 at 12 40 32 PM" src="https://github.com/datalayer/jupyter-ui/assets/14841421/13392b57-c05a-44e7-9a14-27c3c7512efc">

```
info  - Creating an optimized production build
Failed to compile.

../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/node_modules/@jupyterlab/ui-components/style/base.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/node_modules/@jupyterlab/ui-components/style/index.js

Import trace for requested module:
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/node_modules/@jupyterlab/ui-components/style/base.css
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/node_modules/@jupyterlab/ui-components/style/index.js
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/index.js
../../node_modules/@datalayer/jupyter-react/lib/jupyter/lab/JupyterLabCss.js
../../node_modules/@datalayer/jupyter-react/lib/index.js
./components/_Common/jupyter.tsx

../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/node_modules/@jupyterlab/ui-components/style/base.css
Module build failed: Error: Final loader (../../node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String
    at processResult (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:28:395049)
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:28:396519
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:271021
    at iterateNormalLoaders (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:267828)
    at iterateNormalLoaders (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:267913)
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:268142
    at runSyncOrAsync (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:266488)
    at iterateNormalLoaders (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:268045)
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:267687
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:28:395994

Import trace for requested module:
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/node_modules/@jupyterlab/ui-components/style/base.css
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/node_modules/@jupyterlab/ui-components/style/index.js
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/index.js
../../node_modules/@datalayer/jupyter-react/lib/jupyter/lab/JupyterLabCss.js
../../node_modules/@datalayer/jupyter-react/lib/index.js
./components/_Common/jupyter.tsx

../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/base.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/index.js

Import trace for requested module:
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/base.css
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/index.js
../../node_modules/@datalayer/jupyter-react/lib/jupyter/lab/JupyterLabCss.js
../../node_modules/@datalayer/jupyter-react/lib/index.js
./components/_Common/jupyter.tsx

../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/base.css
Module build failed: Error: Final loader (../../node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String
    at processResult (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:28:395049)
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:28:396519
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:271021
    at iterateNormalLoaders (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:267828)
    at iterateNormalLoaders (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:267913)
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:268142
    at runSyncOrAsync (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:266488)
    at iterateNormalLoaders (/Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:268045)
    at /Users/bugzpodder/root/node_modules/next/dist/compiled/webpack/bundle5.js:1:267687
    at /Users/bugzpodder/node_modules/next/dist/compiled/webpack/bundle5.js:28:395994

Import trace for requested module:
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/base.css
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/apputils/style/index.js
../../node_modules/@datalayer/jupyter-react/lib/jupyter/lab/JupyterLabCss.js
../../node_modules/@datalayer/jupyter-react/lib/index.js
./components/_Common/jupyter.tsx

../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/cells/node_modules/@jupyterlab/apputils/style/base.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/cells/node_modules/@jupyterlab/apputils/style/index.js

Import trace for requested module:
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/cells/node_modules/@jupyterlab/apputils/style/base.css
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/cells/node_modules/@jupyterlab/apputils/style/index.js
../../node_modules/@datalayer/jupyter-react/node_modules/@jupyterlab/cells/style/index.js
../../node_modules/@datalayer/jupyter-react/lib/jupyter/lab/JupyterLabCss.js
../../node_modules/@datalayer/jupyter-react/lib/index.js
./components/_Common/jupyter.tsx

```
</pre>
</details>

**Comment by echarles** [comment]
Hi @bugzpodder I see you are using yarn 4? can you confirm? We only run with yarn version 3 (not sure if that makes a diff).

I have updated the [next-js example repository](https://github.com/echarles/jupyter-nextjs-example) to latest jupyter-react 0.9.1. 

To support jupyterl lite kernels (in the browser), you will need to add https://github.com/echarles/jupyter-nextjs-example/commit/64cac0c25b67e2a761c29895720283c7c04d82e0 in your next.config.js

It works fine on my local env.

![Screenshot from 2024-01-20 17-14-47](https://github.com/datalayer/jupyter-ui/assets/226720/6556d4dc-7df3-4db8-83a4-410d5c5ab549)

**Comment by bugzpodder** [comment]
i think the issue might be that i am using pages/ directory, not app/ directory.  I added a bunch of stuff to next-transpire-modules and at least the code builds.  still seeing some console errors but at least this one is resolved..

**Comment by VisheshNucleusTeq** [comment]
what is the solution on this I am still getting this error

**Comment by epshone** [comment]
@bugzpodder I'm having the same issue getting this to run in the pages dir. Are you able to share your config?

**Comment by bugzpodder** [comment]
I had to transpile like 30 different modules in next-transpile-modules..  There were also react compatibility issues. It wasn't worth it and I ended up migrating to apps dir.
