### ISSUE TITLE
On storybook and locally, can't get Lite to actually run a cell.

### ISSUE THREAD

**Issue by doelgonzo** [datalayer/jupyter-ui#329]
## Description

Selecting any of these cells and pressing Shift+Enter is producing no output.  Tried locally and got the same behavior (I added empty metadata objects because it was throwing an error for that in the storybook
https://jupyter-ui-storybook.datalayer.tech/?path=/story/components-notebook--lite-python

## Reproduce

Navigate here: 
https://jupyter-ui-storybook.datalayer.tech/?path=/story/components-notebook--lite-python

1. Select any cell
2. Press Shift+Enter
3. No output will be produced

Tried on different browsers, same result.

## Expected behavior

Maybe I'm missing instructions on how to run Lite?

## Context

- Datalayer version: 
    "@datalayer/jupyter-react": "0.18.12",
- Operating System and version: Mac OS Sonoma 14.3
- Browser and version: Chrome 130.0.6723.117

**Comment by echarles** [comment]
Hi @doelgonzo I have opened https://github.com/datalayer/jupyter-ui/pull/330 to align the storybook code base to the latest changes.

I have also redeployed that branch online. You can try again https://jupyter-ui-storybook.datalayer.tech/?path=/story/components-notebook--lite-python

Make sure you shift-reload (SHIFT-F5), pyodide sometimes cache previous code. Also, I have seen weird response sometimes from micropip (no wheel...), which I have worked around browsing with Incognito Browser (make sure to enable 3rd party cookie if you use that).

[Screencast from 11-19-2024 02:40:11 PM.webm](https://github.com/user-attachments/assets/27ef7775-4f92-40cc-9f5e-e6d283748537)

**Comment by echarles** [comment]
just deployed with micropip which responds better for me

```
import micropip
await micropip.install('ipywidgets')
```

**Comment by doelgonzo** [comment]
Thank you! I see it working now. I got it to run on my environment (using `lite` mode), but only got it working after moving away from `npm` to `yarn`. Not sure why it matters, but it seems that it matters. Also, is there a way ti know the notebook is ready for use? I see pyodide logs showing things are loaded, but not sure if we have a way to know when it's available aside from the active state of the buttons in the toolbar.

**Comment by echarles** [comment]
> Also, is there a way ti know the notebook is ready for use?

You can to listen to the kernel state which are like this (look at the examples folder)

![Screenshot from 2024-11-21 07-53-45](https://github.com/user-attachments/assets/a8713264-2408-442f-bd94-fe7d40830d0c)

**Comment by doelgonzo** [comment]
Thanks for this. Wondering, why does the kernel run when using `yarn` as a package manager but not as `npm` my project is deployed in vercel and yarn is causing issues, so trying to understand what the divergence could be to see if i can patch it up without needing to change package managers

**Comment by doelgonzo** [comment]
gotcha. As for exposing these at a higher level, I would love to contribute some ideas on this, as I think a hook that returns statuses would benefit the react workflow, especially knowing status, as I want to block the Notebook until we get a connected/idle for the first time.

In any case, I have this working on a dev build, but on a production build,  I get the following:
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 597, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 413, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.12/site-packages/piplite/piplite.py", line 117, in _install
    return await micropip.install(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 62, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 151, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 198, in _add_requirement_from_package_index
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 234, in add_wheel
    await wheel.download(self.fetch_kwargs)
  File "/lib/python3.12/site-packages/micropip/wheelinfo.py", line 129, in download
    with zipfile.ZipFile(io.BytesIO(self._data)) as zf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/zipfile/__init__.py", line 1339, in __init__
    self._RealGetContents()
  File "/lib/python312.zip/zipfile/__init__.py", line 1406, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

    at new_error (pyodide.asm.js:10:9958)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:10:123144)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at callPyObjectKwargs (pyodide.asm.js:10:62076)
    at Module.callPyObjectMaybePromising (pyodide.asm.js:10:63254)
    at wrapper (pyodide.asm.js:10:27079)
    at Kn.e.port1.onmessage (pyodide.asm.js:10:99526)
```

Any idea why that would be? Note I only use the in-browser `lite` version. I feel like there's a configuration I'm missing because on dev builds, the save button in the toolbar crashes the app, so gut says I'm missing config.

Note my python is not fully-fluent yet, so it may be something obvious I'm missing.

**Comment by doelgonzo** [comment]
Found that it works if I change this
```
<Jupyter terminals startDefaultKernel>
        <Notebook
              id='notebook-lite-context-id'
              lite
              useRunningKernelIndex={-1}
              CellSidebar={CellSidebar}
              cellSidebarMargin={120}
              Toolbar={NotebookToolbar}
              nbformat={nbformat}
              onSessionConnection={onSessionConnection}
              height='calc(100vh - 200px)'
              renderers={[]}
            />
```
to
```
<Jupyter startDefaultKernel>
        <Notebook
              id='notebook-lite-context-id'
              lite
              useRunningKernelIndex={-1}
              CellSidebar={CellSidebar}
              cellSidebarMargin={120}
              Toolbar={NotebookToolbar}
              nbformat={nbformat}
              onSessionConnection={onSessionConnection}
              height='calc(100vh - 200px)'
              renderers={[]}
            />
```

Not sure why... but hey, it's working now.

**Comment by echarles** [comment]
> Not sure why... but hey, it's working now.

lite relies on a service worker and browser caches, they drive sometimes to weird and unexpected things. Happy you it works for you now.

For the event kernel lifecycle, please open a separated issue to discuss. This has been introduced for the Output working on that with @sok82

**Comment by doelgonzo** [comment]
Seems the error is back, and seems to be exclusive to production build. Any guidance is welcome
<img width="837" alt="image" src="https://github.com/user-attachments/assets/cbba11ae-a2e0-4fa2-8598-4b133867b302">

This is my code:
```
<JupyterReactTheme>
        <Jupyter lite startDefaultKernel>
          <div
            className={cn(
              '[&_.jp-Notebook_.jp-WindowedPanel-viewport]:pr-8',
              '[&_.jp-Notebook-footer]:!w-[calc(100%-244px)]',
              '[&_.jp-Notebook-footer]:opacity-50',
              '[&_[title=Save]]:!hidden' // Hide the save button, which crashes the app...
            )}
          >
            <Notebook
              id='notebook-lite-context-id'
              lite
              useRunningKernelIndex={-1}
              CellSidebar={CellSidebar}
              cellSidebarMargin={120}
              Toolbar={NotebookToolbar}
              nbformat={nbformat}
              onSessionConnection={onSessionConnection}
              height='calc(100vh - 200px)'
              renderers={[]}
            />
          </div>
        </Jupyter>
      </JupyterReactTheme>
```

and this is the json being passed in as `nbformat`:
```
{
  "cells": [
    {
      "cell_type": "code",
      "metadata": {},
      "source": [
        "import micropip\n",
        "await micropip.install('ipywidgets')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python (ipykernel)",
      "language": "python",
      "name": "python"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.10.4"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
```

**Comment by echarles** [comment]
I have seen similar issue while using pyodide and don't think atm we can do a lot, apart from making sure we track the latest versions of the stack and report back those issues to the upstream projects.

**Comment by echarles** [comment]
Closing as fixed, this can be tried on https://jupyter-ui-storybook.datalayer.tech/?path=/story/components-notebook--lite-python

<img width="515" height="322" alt="Image" src="https://github.com/user-attachments/assets/7888a318-c764-4446-b495-848c6dd80980" />
